
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/RPRootDumpReconstructedProton",
  "LCGReflex/RPRootDumpPatternInfo",
  "LCGReflex/RPRootDumpPattern",
  "LCGReflex/RPRootDumpDigiInfo",
  "LCGReflex/RPRootDumpReconstructedProtonPair",
  "LCGReflex/RPRootDumpTrackInfo",
  "LCGReflex/TotemRPEvent",
  "LCGReflex/std::vector<RPRootDumpTrackInfo>",
  "LCGReflex/std::vector<RPRootDumpReconstructedProton>",
  "LCGReflex/std::vector<RPRootDumpPatternInfo>",
  "LCGReflex/std::vector<RPRootDumpDigiInfo>",
  "LCGReflex/std::map<unsigned int,RPRootDumpReconstructedProton>",
  "LCGReflex/std::map<unsigned int,std::vector<RPRootDumpTrackInfo> >",
  "LCGReflex/std::map<unsigned int,RPRootDumpPatternInfo>",
  "LCGReflex/std::map<unsigned int,RPRootDumpDigiInfo>",
  "LCGReflex/std::map<unsigned int,RPRootDumpTrackInfo>",
  "LCGReflex/edm::Wrapper<std::map<unsigned int,RPRootDumpReconstructedProton> >",
  "LCGReflex/edm::Wrapper<std::map<unsigned int,std::vector<RPRootDumpTrackInfo> > >",
  "LCGReflex/edm::Wrapper<std::map<unsigned int,RPRootDumpPatternInfo> >",
  "LCGReflex/edm::Wrapper<std::map<unsigned int,RPRootDumpDigiInfo> >",
  "LCGReflex/edm::Wrapper<std::map<unsigned int,RPRootDumpTrackInfo> >",
  "LCGReflex/edm::Wrapper<std::vector<RPRootDumpReconstructedProton> >",
  "LCGReflex/edm::Wrapper<std::vector<RPRootDumpPatternInfo> >",
  "LCGReflex/edm::Wrapper<std::vector<RPRootDumpDigiInfo> >",
  "LCGReflex/edm::Wrapper<std::vector<RPRootDumpTrackInfo> >",
  "LCGReflex/edm::Wrapper<RPRootDumpPatternInfo>",
  "LCGReflex/edm::Wrapper<RPRootDumpPattern>",
  "LCGReflex/edm::Wrapper<RPRootDumpReconstructedProtonPair>",
  "LCGReflex/edm::Wrapper<RPRootDumpReconstructedProton>",
  "LCGReflex/edm::Wrapper<RPRootDumpDigiInfo>",
  "LCGReflex/edm::Wrapper<RPRootDumpTrackInfo>",
  "LCGReflex/edm::Wrapper<TotemRPEvent>",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

