
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc493/src/TotemAnalysis/TotemAnalysisEvent/src/TotemAnalysisTotemAnalysisEvent/a/TotemAnalysisTotemAnalysisEvent_xr.cc_tmp
 "LCGReflex/TotemRPEvent",
 "LCGReflex/RPRootDumpTrackInfo",
 "LCGReflex/RPRootDumpDigiInfo",
 "LCGReflex/RPRootDumpReconstructedProton",
 "LCGReflex/RPRootDumpReconstructedProtonPair",
 "LCGReflex/RPRootDumpPattern",
 "LCGReflex/RPRootDumpPatternInfo",
 "LCGReflex/std::vector<RPRootDumpTrackInfo>",
 "LCGReflex/vector<RPRootDumpTrackInfo>",
 "LCGReflex/std::vector<RPRootDumpDigiInfo>",
 "LCGReflex/vector<RPRootDumpDigiInfo>",
 "LCGReflex/std::vector<RPRootDumpPatternInfo>",
 "LCGReflex/vector<RPRootDumpPatternInfo>",
 "LCGReflex/std::vector<RPRootDumpReconstructedProton>",
 "LCGReflex/vector<RPRootDumpReconstructedProton>",
 "LCGReflex/std::map<unsigned int,RPRootDumpTrackInfo>",
 "LCGReflex/map<unsigned int,RPRootDumpTrackInfo>",
 "LCGReflex/std::map<unsigned int,RPRootDumpDigiInfo>",
 "LCGReflex/map<unsigned int,RPRootDumpDigiInfo>",
 "LCGReflex/std::map<unsigned int,RPRootDumpPatternInfo>",
 "LCGReflex/map<unsigned int,RPRootDumpPatternInfo>",
 "LCGReflex/std::map<unsigned int,std::vector<RPRootDumpTrackInfo> >",
 "LCGReflex/map<unsigned int,vector<RPRootDumpTrackInfo> >",
 "LCGReflex/std::map<unsigned int,RPRootDumpReconstructedProton>",
 "LCGReflex/map<unsigned int,RPRootDumpReconstructedProton>",
 "LCGReflex/edm::Wrapper<TotemRPEvent>",
 "LCGReflex/edm::Wrapper<RPRootDumpTrackInfo>",
 "LCGReflex/edm::Wrapper<RPRootDumpDigiInfo>",
 "LCGReflex/edm::Wrapper<RPRootDumpReconstructedProton>",
 "LCGReflex/edm::Wrapper<RPRootDumpReconstructedProtonPair>",
 "LCGReflex/edm::Wrapper<RPRootDumpPattern>",
 "LCGReflex/edm::Wrapper<RPRootDumpPatternInfo>",
 "LCGReflex/edm::Wrapper<std::vector<RPRootDumpTrackInfo> >",
 "LCGReflex/edm::Wrapper<vector<RPRootDumpTrackInfo> >",
 "LCGReflex/edm::Wrapper<std::vector<RPRootDumpDigiInfo> >",
 "LCGReflex/edm::Wrapper<vector<RPRootDumpDigiInfo> >",
 "LCGReflex/edm::Wrapper<std::vector<RPRootDumpPatternInfo> >",
 "LCGReflex/edm::Wrapper<vector<RPRootDumpPatternInfo> >",
 "LCGReflex/edm::Wrapper<std::vector<RPRootDumpReconstructedProton> >",
 "LCGReflex/edm::Wrapper<vector<RPRootDumpReconstructedProton> >",
 "LCGReflex/edm::Wrapper<std::map<unsigned int,RPRootDumpTrackInfo> >",
 "LCGReflex/edm::Wrapper<map<unsigned int,RPRootDumpTrackInfo> >",
 "LCGReflex/edm::Wrapper<std::map<unsigned int,RPRootDumpDigiInfo> >",
 "LCGReflex/edm::Wrapper<map<unsigned int,RPRootDumpDigiInfo> >",
 "LCGReflex/edm::Wrapper<std::map<unsigned int,RPRootDumpPatternInfo> >",
 "LCGReflex/edm::Wrapper<map<unsigned int,RPRootDumpPatternInfo> >",
 "LCGReflex/edm::Wrapper<std::map<unsigned int,std::vector<RPRootDumpTrackInfo> > >",
 "LCGReflex/edm::Wrapper<map<unsigned int,vector<RPRootDumpTrackInfo> > >",
 "LCGReflex/edm::Wrapper<std::map<unsigned int,RPRootDumpReconstructedProton> >",
 "LCGReflex/edm::Wrapper<map<unsigned int,RPRootDumpReconstructedProton> >",
//--End   tmp/slc6_amd64_gcc493/src/TotemAnalysis/TotemAnalysisEvent/src/TotemAnalysisTotemAnalysisEvent/a/TotemAnalysisTotemAnalysisEvent_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
