
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/T2Cluster",
  "LCGReflex/cluster_entry",
  "LCGReflex/T2ROGeometry",
  "LCGReflex/std::pair<T2DetId,std::vector<T2Cluster> >",
  "LCGReflex/std::vector<T2Cluster>",
  "LCGReflex/std::vector<cluster_entry>",
  "LCGReflex/edm::Wrapper<std::pair<T2DetId,std::vector<T2Cluster> > >",
  "LCGReflex/std::map<T2DetId,std::vector<T2Cluster> >",
  "LCGReflex/edm::Wrapper<std::map<T2DetId,std::vector<T2Cluster> > >",
  "LCGReflex/edm::Wrapper<std::vector<std::map<T2DetId,std::vector<T2Cluster> > > >",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

