
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/RPCCBits",
  "LCGReflex/T1TriggerBits",
  "LCGReflex/T2TriggerBits",
  "LCGReflex/std::vector<T2TriggerBits>",
  "LCGReflex/std::vector<T1TriggerBits>",
  "LCGReflex/std::vector<RPCCBits>",
  "LCGReflex/edm::Wrapper<std::vector<T2TriggerBits> >",
  "LCGReflex/edm::Wrapper<T2TriggerBits>",
  "LCGReflex/edm::Wrapper<std::vector<T1TriggerBits> >",
  "LCGReflex/edm::Wrapper<T1TriggerBits>",
  "LCGReflex/edm::Wrapper<std::vector<RPCCBits> >",
  "LCGReflex/edm::Wrapper<RPCCBits>",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

