#!/bin/tcsh
cd /afs/cern.ch/user/e/eliza/private/TOTEM_JPSI/RPSIM/CMSSW_7_1_21/src
cmsenv
rehash


#cd /afs/cern.ch/user/e/eliza/private/TOTEM_JPSI/RPSIM/CMSSW_7_1_21/src/Configs


echo "Running step1_CMSOnly_updated_1.py"
cmsRun step1_CMSOnly_generatedpw.py

#cp /afs/cern.ch/user/e/eliza/private/TOTEM_JPSI/RPSIM/CMSSW_7_1_21/src/step1_SDPlusPomwig_RPRECO_CMS_SIM_oficialChain.root /afs/cern.ch/user/e/eliza/private/TOTEM_JPSI/RPSIM/CMSSW_7_1_21/src/RootFiles
