
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/RPDetTrigger",
  "LCGReflex/RPDigCluster",
  "LCGReflex/RPTimingDetectorHit",
  "LCGReflex/RPRecoHit",
  "LCGReflex/RPStripDigi",
  "LCGReflex/std::pair<__gnu_cxx::__normal_iterator<const RPRecoHit*,std::vector<RPRecoHit> >,__gnu_cxx::__normal_iterator<const RPRecoHit*,std::vector<RPRecoHit> > >",
  "LCGReflex/std::vector<RPTimingDetectorHit>",
  "LCGReflex/edm::DetSet<RPDigCluster>",
  "LCGReflex/std::vector<edm::DetSet<RPDigCluster> >",
  "LCGReflex/std::vector<RPDigCluster>",
  "LCGReflex/edm::DetSet<RPDetTrigger>",
  "LCGReflex/std::vector<edm::DetSet<RPDetTrigger> >",
  "LCGReflex/std::vector<RPDetTrigger>",
  "LCGReflex/std::vector<RPRecoHit>",
  "LCGReflex/std::vector<const RPRecoHit*>",
  "LCGReflex/edm::DetSet<RPRecoHit>",
  "LCGReflex/std::vector<edm::DetSet<RPRecoHit> >",
  "LCGReflex/edm::DetSet<RPStripDigi>",
  "LCGReflex/std::vector<edm::DetSet<RPStripDigi> >",
  "LCGReflex/std::vector<RPStripDigi>",
  "LCGReflex/edm::Wrapper<std::vector<RPTimingDetectorHit> >",
  "LCGReflex/edm::DetSetVector<RPDigCluster>",
  "LCGReflex/edm::Wrapper<edm::DetSetVector<RPDigCluster> >",
  "LCGReflex/edm::DetSetVector<RPDetTrigger>",
  "LCGReflex/edm::Wrapper<edm::DetSetVector<RPDetTrigger> >",
  "LCGReflex/edm::Wrapper<edm::DetSet<RPDetTrigger> >",
  "LCGReflex/edm::DetSetVector<RPRecoHit>",
  "LCGReflex/edm::Wrapper<edm::DetSetVector<RPRecoHit> >",
  "LCGReflex/edm::DetSetVector<RPStripDigi>",
  "LCGReflex/edm::Wrapper<edm::DetSetVector<RPStripDigi> >",
  "LCGReflex/edm::Wrapper<edm::DetSet<RPStripDigi> >",
  "LCGReflex/__gnu_cxx::__normal_iterator<const RPRecoHit*,std::vector<RPRecoHit> >",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

