/********************************************************************
* tmp/slc6_amd64_gcc481/src/TotemAnalysis/T2DEVNtuplizer/src/TotemAnalysisT2DEVNtuplizer/LinkDef.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/slc6_amd64_gcc481/src/TotemAnalysis/T2DEVNtuplizer/src/TotemAnalysisT2DEVNtuplizer/LinkDef.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLinkDef();
extern void G__cpp_setup_inheritanceLinkDef();
extern void G__cpp_setup_typetableLinkDef();
extern void G__cpp_setup_memvarLinkDef();
extern void G__cpp_setup_globalLinkDef();
extern void G__cpp_setup_memfuncLinkDef();
extern void G__cpp_setup_funcLinkDef();
extern void G__set_cpp_environmentLinkDef();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LinkDefLN_TClass;
extern G__linked_taginfo G__LinkDefLN_TBuffer;
extern G__linked_taginfo G__LinkDefLN_TMemberInspector;
extern G__linked_taginfo G__LinkDefLN_TObject;
extern G__linked_taginfo G__LinkDefLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__LinkDefLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__LinkDefLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LinkDefLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDefLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LinkDefLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDefLN_T2EventDEV;
extern G__linked_taginfo G__LinkDefLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__LinkDefLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
