from CRABClient.UserUtilities import config
config = config()
#config.General.requestName = 'DIGI-HLT_Production_CMS-RP-NewFormat-PYTHIA8Dijets-pT20GeV'
config.General.requestName = 'DIGI-HLT_Production_CMS-RP-NewFormat-POMWIGSDMinusDijets-pT20GeV-v1' 
config.General.workArea = 'crab_projects'
config.JobType.pluginName = 'Analysis'
#config.JobType.pluginName = 'PrivateMC' 
#config.Data.outputPrimaryDataset = 'Production_CMSSIM-DIGI-HLT-RPRECO-NewFormat-PYTHIA8Dijets-pT20GeV'
config.General.transferOutputs = True
config.General.transferLogs = True
#config.JobType.generator = 'lhe'
config.JobType.psetName = 'DIGI_HLT_cfg_run2_mc_25nsLowPU.py'
config.JobType.outputFiles = ['step1_DIGI_L1_DIGI2RAW_HLT.root']
#config.Data.userInputFiles = open('inputfile_CMSSIM_v2.txt').readlines()
#config.JobType.inputFiles = ['/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_1.root','gci/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_2.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_3.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_4.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_5.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_6.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_7.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_8.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_9.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_10.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_11.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_12.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_13.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_14.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_15.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_16.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_17.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_18.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_19.root','/store/caf/user/eliza/validation/cmstotem/RP-GEN-SIM-RECO_v4/MBRPythia8_RPRECO_20.root']
#config.Data.inputDataset = '/Production_CMSSIM-RPRECO_PYTHIA8-Dijets_v2/eliza-crab_SIM_Production_CMS-RP_PYTHIA8-Dijets_v2-2b59b7f3283bf5a65771a78c5398e9d3/USER'
config.Data.inputDataset = '/Production_CMSSIM-RPRECO_POMWIG-SDMinusDijets_v1/eliza-crab_SIM_Production_CMS-RP_POMWIG-SDMinusDijets_v1-2b59b7f3283bf5a65771a78c5398e9d3/USER'
config.Data.inputDBS = 'phys03'
config.Data.outputDatasetTag = 'Production_CMSSIM-DIGI-HLT-RPRECO-NewFormat-POMWIGSDMinusDijets-pT20GeV-v1'
#config.Data.outputDatasetTag = 'Production_CMSSIM-DIGI-HLT-RPRECO-NewFormat-PYTHIA8Dijets-pT20GeV'
#config.Data.splitting = 'EventBased'
config.Data.splitting = 'FileBased'
config.Data.unitsPerJob = 1
NJOBS = 234
config.Data.totalUnits = config.Data.unitsPerJob * NJOBS
#config.Data.outLFNDirBase = '/store/group/phys_diffraction/CMSTotemLowPU2015/emc/MC/pythia8/step2' # or '/store/group/<subdir>'
config.Data.outLFNDirBase = '/store/group/phys_diffraction/CMSTotemLowPU2015/emc/MC/pomwig/sdminus/step2'
#config.Data.outLFNDirBase = '/store/user/eliza/' 
config.Data.publication = True
#config.Data.publishDataName = 'DIGI-RECO-MBR-CMSTOTEM'
config.Site.whitelist = ['T2_CH_CERN']
config.Site.storageSite = 'T2_CH_CERN'
#config.Site.storageSite = 'T2_BR_UERJ'
