
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/TotemDigiCollection<T1DetId,T1DigiVfat>",
  "LCGReflex/T1DigiVfat",
  "LCGReflex/std::pair<T1DetId,std::vector<T1DigiVfat> >",
  "LCGReflex/std::vector<T1DigiVfat>",
  "LCGReflex/std::map<T1DetId,std::vector<T1DigiVfat> >",
  "LCGReflex/edm::Wrapper<std::pair<T1DetId,std::vector<T1DigiVfat> > >",
  "LCGReflex/edm::Wrapper<TotemDigiCollection<T1DetId,T1DigiVfat> >",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

