/********************************************************************
* ../src/eventdictT.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/eventdictT.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableeventdictT();
extern void G__cpp_setup_inheritanceeventdictT();
extern void G__cpp_setup_typetableeventdictT();
extern void G__cpp_setup_memvareventdictT();
extern void G__cpp_setup_globaleventdictT();
extern void G__cpp_setup_memfunceventdictT();
extern void G__cpp_setup_funceventdictT();
extern void G__set_cpp_environmenteventdictT();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/T2Event.h"
#include "../src/T1Event.h"
#include "../src/TriggerData.h"
#include "../src/EventMetaData.h"
#include "../src/RPRootDumpDigiInfo.h"
#include "../src/RPEvent.h"
#include "../src/RPRootDumpPattern.h"
#include "../src/RPRootDumpPatternInfo.h"
#include "../src/RPRootDumpReconstructedProton.h"
#include "../src/RPRootDumpReconstructedProtonPair.h"
#include "../src/RPRootDumpTrackInfo.h"
#include "../src/NtupleInfo.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__eventdictTLN_TClass;
extern G__linked_taginfo G__eventdictTLN_TBuffer;
extern G__linked_taginfo G__eventdictTLN_TMemberInspector;
extern G__linked_taginfo G__eventdictTLN_TObject;
extern G__linked_taginfo G__eventdictTLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__eventdictTLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__eventdictTLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__eventdictTLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictTLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__eventdictTLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictTLN_T2Event;
extern G__linked_taginfo G__eventdictTLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__eventdictTLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictTLN_T1Event;
extern G__linked_taginfo G__eventdictTLN_TriggerData;
extern G__linked_taginfo G__eventdictTLN_EventMetaData;
extern G__linked_taginfo G__eventdictTLN_RPRootDumpDigiInfo;
extern G__linked_taginfo G__eventdictTLN_RPRootDumpReconstructedProton;
extern G__linked_taginfo G__eventdictTLN_RPRootDumpReconstructedProtonPair;
extern G__linked_taginfo G__eventdictTLN_RPEvent;
extern G__linked_taginfo G__eventdictTLN_RPRootDumpPattern;
extern G__linked_taginfo G__eventdictTLN_RPRootDumpPatternInfo;
extern G__linked_taginfo G__eventdictTLN_vectorlERPRootDumpPatterncOallocatorlERPRootDumpPatterngRsPgR;
extern G__linked_taginfo G__eventdictTLN_reverse_iteratorlEvectorlERPRootDumpPatterncOallocatorlERPRootDumpPatterngRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventdictTLN_RPRootDumpTrackInfo;
extern G__linked_taginfo G__eventdictTLN_NtupleInfo;
extern G__linked_taginfo G__eventdictTLN_maplEunsignedsPintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__eventdictTLN_vectorlERPRootDumpTrackInfocOallocatorlERPRootDumpTrackInfogRsPgR;
extern G__linked_taginfo G__eventdictTLN_vectorlERPRootDumpTrackInfocOallocatorlERPRootDumpTrackInfogRsPgRcLcLiterator;
extern G__linked_taginfo G__eventdictTLN_reverse_iteratorlEvectorlERPRootDumpTrackInfocOallocatorlERPRootDumpTrackInfogRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<RPRootDumpTrackInfo,allocator<RPRootDumpTrackInfo> > G__vectorlERPRootDumpTrackInfocOallocatorlERPRootDumpTrackInfogRsPgR;
