
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/TotemRPHistoClass",
  "LCGReflex/TotemRPHistoClass::Hit",
  "LCGReflex/std::vector<TotemRPHistoClass::Hit>",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

