
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/T2Road",
  "LCGReflex/std::vector<T2Road>",
  "LCGReflex/edm::Wrapper<std::vector<T2Road> >",
  "LCGReflex/edm::Wrapper<std::vector<std::vector<T2Road> > >",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

