
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/T2DigiVfat",
  "LCGReflex/TotemDigiCollection<T2DetId,T2DigiVfat>",
  "LCGReflex/std::pair<T2DetId,std::vector<T2DigiVfat> >",
  "LCGReflex/std::vector<T2DigiVfat>",
  "LCGReflex/std::map<T2DetId,std::vector<T2DigiVfat> >",
  "LCGReflex/edm::Wrapper<std::pair<T2DetId,std::vector<T2DigiVfat> > >",
  "LCGReflex/edm::Wrapper<TotemDigiCollection<T2DetId,T2DigiVfat> >",
  "LCGReflex/std::map<unsigned int,unsigned int>",
  "LCGReflex/edm::Wrapper<std::map<unsigned int,unsigned int> >",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

