
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/MillepedeAlgorithm",
  "LCGReflex/AlignmentTask",
  "LCGReflex/AlignmentConstraint",
  "LCGReflex/IdealResult",
  "LCGReflex/SingularMode",
  "LCGReflex/AlignmentGeometry",
  "LCGReflex/JanAlignmentAlgorithm",
  "LCGReflex/LocalTrackFitter",
  "LCGReflex/DetGeometry",
  "LCGReflex/std::vector<TGraph*>",
  "LCGReflex/std::vector<TH1D*>",
  "LCGReflex/std::vector<SingularMode>",
  "LCGReflex/std::vector<AlignmentConstraint>",
  "LCGReflex/std::set<unsigned int>",
  "LCGReflex/std::map<std::set<unsigned int>,JanAlignmentAlgorithm::ScatterPlot>",
  "LCGReflex/std::map<unsigned int,JanAlignmentAlgorithm::DetStat>",
  "LCGReflex/std::map<unsigned int,DetGeometry>",
  "LCGReflex/JanAlignmentAlgorithm::ScatterPlot",
  "LCGReflex/JanAlignmentAlgorithm::DetStat",
  "LCGReflex/std::map<unsigned int,TVectorT<double> >",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

